home: http://www.litejs.com
name: litejs
author: Lauri Rooden
email: lauri@rooden.ee
paginate: 25
permalink: /:title/
markdown: rdiscount
pygments: true
exclude:
- README.md
menu:
- projects
- contact
