name: litejs
author: Lauri Rooden
home: http://www.litejs.com
url: http://www.litejs.com
email: lauri@rooden.ee
ga: UA-22792206-4
paginate: 25
permalink: /:title/
kramdown:
    input: GFM
highlighter: rouge
gems: [jekyll-paginate, jekyll-gist]
exclude:
- README.md
menu:
- projects
- contact
