name: litejs
author: Lauri Rooden
home: http://www.litejs.com
url: http://www.litejs.com
email: lauri@rooden.ee
ga: UA-22792206-4
paginate: 25
permalink: /:title/
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
exclude:
- README.md
menu:
- projects
- contact
